### ISSUE TITLE
CSV writer is crashing with UTF-8 strings

### ISSUE THREAD

**Issue by cedricraud** [guardian/athena-cli#20]
When trying to use athena-cli in batch mode with CSV output, a exception is raised because of UTF-8 characters in the results:

```
Traceback (most recent call last):
  File "/usr/local/bin/athena", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/athena_cli.py", line 402, in main
    batch.execute(statement=args.execute)
  File "/usr/local/lib/python2.7/site-packages/athena_cli.py", line 58, in execute
    csv_writer.writerows([row for row in self.athena.yield_rows(results, headers)])
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 13: ordinal not in range(128)
```

The problem seems to lie in the native `csv` library of Python 2.x which [does not support UTF-8 strings](https://stackoverflow.com/a/35444608) by default.

**Comment by satterly** [comment]
Thanks for reporting the issue *and* providing the fix. The fixed version (0.1.4) is available on PyPI immediately.
