### ISSUE TITLE
Error on Redhat 7.4

### ISSUE THREAD

**Issue by ghost** [guardian/athena-cli#27]
I installed athenacli using pip3 and when i run athena i get the following error
athena
Traceback (most recent call last):
  File "/usr/bin/athena", line 7, in <module>
    from athena_cli import main
  File "/usr/lib/python3.4/site-packages/athena_cli.py", line 69, in <module>
    del cmd.Cmd.do_show  # "show" is an Athena command
AttributeError: do_show

**Comment by satterly** [comment]
please type `pip3 list` and paste output below. thanks.

**Comment by ghost** [comment]
Here is the output from pip3 list
athena-cli (0.1.7)
awscli (1.14.35)
boto3 (1.5.25)
botocore (1.8.39)
cmd2 (0.8.0)
colorama (0.3.7)
contextlib2 (0.5.5)
docutils (0.14)
jmespath (0.9.3)
pip (9.0.1)
pyasn1 (0.4.2)
pyparsing (2.2.0)
pyperclip (1.6.0)
python-dateutil (2.6.1)
PyYAML (3.12)
rsa (3.4.2)
s3transfer (0.1.12)
setuptools (19.2)
six (1.11.0)
tabulate (0.8.2)

please let me know if you need more information.

**Comment by ghost** [comment]
@satterly Do you have an update on this issue ?

**Comment by satterly** [comment]
Looks like there's been a change with the release of Cmd2 0.8.0. Downgrading Cmd2 to 0.7.8 will get `athena` working while I look into the root cause.

```
$ pip3 install cmd2==0.7.8
```

**Comment by satterly** [comment]
This is fixed in version 0.1.8.
```
$ pip install athena-cli --upgrade
```

**Comment by ghost** [comment]
@satterly It looks like the original issue is fixed. 
Different topic, is it ok if i use instance based access instead of user based ? I am running this on aws ec2 instances and attached read access role for athena on these instances but when i run "athena" it says botocore.exceptions.NoRegionError: You must specify a region.
Please let me know what to do.

**Comment by satterly** [comment]
Stupid question but does it work if you specify a region? You can do so at the command line ...
```
$ athena --region eu-west-1
```

**Comment by ghost** [comment]
@satterly ```$ athena --region eu-west-1``` worked but even after providing full access to the instance it displays the following error:
`Query rfasdfsgewrte4535-gdgdsg-4gfdgsdg6cb-8f40-4532536437y365uygrhr, FAILED
Insufficient permissions to execute the query.`

**Comment by satterly** [comment]
This has nothing to do with the `athena` CLI. You need to configure user permissions to allow you to run queries. See "Attach Managed Policies for Using Athena" at https://docs.aws.amazon.com/athena/latest/ug/setting-up.html
