### ISSUE TITLE
Another Athena CLI tool

### ISSUE THREAD

**Issue by zzl0** [guardian/athena-cli#37]
Hello, it seems we have a common interest, we also have created an [AthenaCLI](https://github.com/dbcli/athenacli) tool that can do auto-completion and syntax highlighting. Please try it out if you are interested in it. And I am wondering if you'd like to link to it from your README, like this we did in our README: https://github.com/dbcli/athenacli#similar-projects

![](https://github.com/dbcli/athenacli/raw/master/docs/_static/gif/athenacli.gif)

**Comment by satterly** [comment]
Nice work. Yes, I'll link from the README at https://github.com/satterly/athena-cli/blob/master/README.md as the project has moved to https://github.com/satterly/athena-cli -- maybe you could update your link? Thanks.

**Comment by zzl0** [comment]
Thanks, I update the link in [dbcli/athenacli](https://github.com/dbcli/athenacli#similar-projects)
